on:
  # push:
  #   branches:
  #   - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1
        with:
          src_dir: template-dummy
          dest_dir: template-dummy
          account_id: ${{ vars.hubspot_account_id || secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}